version: "3.9"

services:
  app:
    build: ./app
    container_name: noframework-app
    environment:
      - APP_PORT=3000
      - SOCKET_PORT=5000
      - SOCKET_HOST=127.0.0.1
      - MONGO_URI=mongodb://mongo:27017/
      - MONGO_DB=messages_db
      - MONGO_COLLECTION=messages
    ports:
      - "3000:3000"
      - "5000:5000"
    depends_on:
      - mongo
    volumes:
      - ./app:/app:ro

  mongo:
    image: mongo:7
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
